POST http://localhost:3000/bridge/create
Content-Type: application/json

###

POST http://localhost:3000/bridge/add-players
Content-Type: application/json

{
  "players": ["Kristoffer", "Stine", "Player3", "Player4"]
}

###

POST http://localhost:3000/bridge/bid
Content-Type: application/json

{
  "playerName": "Stine",
  "bid": "3"
}

###

GET http://localhost:3000/bridge/list-players
Content-Type: application/json

###

POST http://localhost:3000/bridge/restart
Content-Type: application/json

###

GET http://localhost:3000/bridge/teams
